In [4]:
import numpy as np
ar=np.array([7,5,2,6,2,3])
print(ar)

[7 5 2 6 2 3]


In [3]:
import numpy as np
ar=np.array([[7,5],[2,6],[2,3]])
print(ar)

[[7 5]
 [2 6]
 [2 3]]


In [5]:
import numpy as np
ar=np.zeros((2,3))
print(ar)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np
ar=np.zeros((2,3))
print("The elements in the array:\n",ar)

The elements in the array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
import numpy as np
ar=np.full((2,3),6)
print(ar)

[[6 6 6]
 [6 6 6]]


In [13]:
import numpy as np
ar=np.random.random((2,3))
print(ar)

[[0.58646215 0.56363313 0.92940745]
 [0.53476203 0.13391371 0.15427552]]


In [15]:
import numpy as np
ar=np.arange(2,20,2)
print(ar)

[ 2  4  6  8 10 12 14 16 18]


In [20]:
import numpy as np
ar=np.array([[7,5],[2,6],[2,3]])
print("original array:",ar.ndim)
print(ar)
arr=ar.reshape(2,3)
print("reshaped array:",arr.ndim)
print(arr)
arrr=arr.flatten()
print("flattened array:",arrr.ndim)
print(arrr)

original array: 2
[[7 5]
 [2 6]
 [2 3]]
reshaped array: 2
[[7 5 2]
 [6 2 3]]
flattened array: 1
[7 5 2 6 2 3]


In [21]:
import numpy as np
ar=np.array([[7,5],[2,6],[2,3]])
print(ar.size)

6


In [22]:
import numpy as np
ar=np.array([[7,5],[2,6],[2,3]])
print(ar.shape)

(3, 2)


In [23]:
import numpy as np
ar=np.array([[7,5],[2,6],[2,3]])
print(ar.dtype)

int32


In [24]:
import numpy as np
ar=np.array([[7,5],[2,6],[2,3]])
ara=ar.astype('f')
print(ara)

[[7. 5.]
 [2. 6.]
 [2. 3.]]


In [27]:
import numpy as np
ar=np.random.random((2,3))
print(ar.astype('i'))

[[0 0 0]
 [0 0 0]]


In [29]:
import numpy as np
ar=np.array([7,5,2,6,2,3])
print(ar[0:5:2])

[7 2 2]


In [32]:
import numpy as np
ar=np.array([[7,5,8,9,0],[2,6,4,2,5],[2,3,7,4,5]])
print(ar[0,1:3])

[5 8]


In [33]:
import numpy as np
ar=np.array([[7,5,8,9,0],[2,6,4,2,5],[2,3,7,4,5]])
print(ar[1:,1:])

[[6 4 2 5]
 [3 7 4 5]]


In [34]:
import numpy as np
ar=np.array([[7,5,8,9,0],[2,6,4,2,5],[2,3,7,4,5]])
print(ar[:,1])

[5 6 3]


In [3]:
import numpy as np
import pandas as pd

data = {'Name': ['Teodosija', 'Sutton', 'Taneli', 'David', 'Ross'],
        'Age': [25, 30, 22, 35, 28],
        'Salary': [50000, 60000, 45000, 70000, 55000]}
df = pd.DataFrame(data)
print(data)

{'Name': ['Teodosija', 'Sutton', 'Taneli', 'David', 'Ross'], 'Age': [25, 30, 22, 35, 28], 'Salary': [50000, 60000, 45000, 70000, 55000]}


In [2]:
import numpy as np
ar=np.array([[7,5,8,9,0],[2,6,4,2,5],[2,3,7,4,5]])
temp=ar[[0,1,2],[2,1,0]]
print(temp)

[8 6 2]


In [8]:
import numpy as np
ar=np.array([[7,5,8,1,0],[2,6,4,2,5],[2,3,7,4,5]])
c=ar>2
t=ar[c]
print(t)

[7 5 8 6 4 5 3 7 4 5]


In [9]:
import numpy as np
ar=np.array([7,5,8,9,0])
print(ar[::2])

[7 8 0]


In [11]:
import numpy as np
ar=np.array([7,5,8,9,0])
arr=np.array([2,6,4,2,5])
a=np.concatenate((ar,arr))
print(a)

[7 5 8 9 0 2 6 4 2 5]


In [12]:
import numpy as np
ar=np.array([7,5,8,9,0])
arr=np.array([2,6,4,2,5])
arrr=np.hstack((ar,arr))
print(arrr)

[7 5 8 9 0 2 6 4 2 5]


In [13]:
import numpy as np
ar=np.array([7,5,8,9,0])
arr=np.array([2,6,4,2,5])
arrr=np.vstack((ar,arr))
print(arrr)

[[7 5 8 9 0]
 [2 6 4 2 5]]


In [14]:
import numpy as np
ar=np.array([7,5,8,9,0])
arr=np.array([2,6,4,2,5])
arrr=np.dstack((ar,arr))
print(arrr)

[[[7 2]
  [5 6]
  [8 4]
  [9 2]
  [0 5]]]


In [15]:
import numpy as np
ar=np.array([7,5,8,9,0])
arr=np.array_split(ar,2)
print(arr)

[array([7, 5, 8]), array([9, 0])]


In [17]:
import numpy as np
ar=np.array([7,5,8,9,0])
arr=np.array_split(ar,2)
for i in range(0,len(arr)):
    print(arr[i])

[7 5 8]
[9 0]


In [19]:
import numpy as np
ar=np.array([7,5,8,9,0,2,6,4,2,5])
a=np.where(ar==2)
print(a)

(array([5, 8], dtype=int64),)


In [20]:
import numpy as np
ar=np.array([7,5,8,9,0,2,6,4,2,5])
a=np.where(ar%2==0)
print(a)

(array([2, 4, 5, 6, 7, 8], dtype=int64),)


In [5]:
import numpy as np
ar=np.array([0,2,4,5,6,7,8,9,30])
a=np.searchsorted(ar,4,side='left')
print(a)

2


In [14]:
import numpy as np
ar=np.array([0,2,4,5,6,7,8,9,30])
a=np.searchsorted(ar,20,side='right')
print(a)

8


In [6]:
import numpy as np
ar=np.array([7,5,8,9,0,2,6,4,2,5])
a=np.sort(ar)
print(a)

[0 2 2 4 5 5 6 7 8 9]


In [7]:
import numpy as np
ar=np.array([[7,5,2],[6,2,3]])
a=np.sort(ar)
print(a)

[[2 5 7]
 [2 3 6]]


In [9]:
import numpy as np
ar=np.array([7,5,2,6])
x=[False,True,False,True]
n=ar[x]
print(ar,'\n',x,'\n',n)

[7 5 2 6] 
 [False, True, False, True] 
 [5 6]


In [11]:
import numpy as np
ar=np.array([7,5,2,6,2,3])
x=ar>3
n=ar[x]
print(ar,'\n',x,'\n',n)

[7 5 2 6 2 3] 
 [ True  True False  True False False] 
 [7 5 6]


In [12]:
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([2,4,6,8,10])
print(a)
print(b)


[10 20 30 40 50]
[ 2  4  6  8 10]


In [15]:
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([2,4,6,8,10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.dot(b))

[12 24 36 48 60]
[ 8 16 24 32 40]
[ 20  80 180 320 500]
[5. 5. 5. 5. 5.]
1100


In [16]:
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([2,4,6,8,10])
s=8
print(s,'\n',a,'\n',a*s)

8 
 [10 20 30 40 50] 
 [ 80 160 240 320 400]


In [19]:
def my(x,y):
    if x>y:
        return x-y
    else:
        return x+y
a=[10,2,20,3]
b=[4,30,5,40]
vec=np.vectorize(my)
print(a)
print(b)
print("output")
print(vec(a,b))

[10, 2, 20, 3]
[4, 30, 5, 40]
output
[ 6 32 15 43]
